name: Lamplight Studio
favicon: null
layout_spectrum: 0.7439252070616931
typography_spectrum: 0.5876315433997661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2c166'
    - '#3b8a7d'
    - '#b22514'
    - '#0f2f40'
  brandStrength: 0.3125
  lightness: 0.1954828870948404
  saturation: 0.41386474878527224
  rhythmicContrast: 0.9953730157576501
purpose: []
