name: Lamplight Studio
favicon: null
layout_spectrum: 0.75007
typography_spectrum: 0.5876315433997661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d85529'
    - '#fdcf31'
    - '#f1c4b4'
    - '#ffe281'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
